name: Example for minimal setup
on:
  push:
    branches:
      - develop

jobs:
  benchmark:
    name: Run minimal steps to run github-action-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Run benchmark
        run: |
          cd examples/pytest
          pip install -r requirements.txt
          pytest bench.py --benchmark-json output.json
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: chrisjsewell/github-action-benchmark@v1
        with:
          output-file-path: examples/pytest/output.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
